# Generated by Django 4.0 on 2022-02-12 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='fil',
            field=models.FileField(upload_to='home/files/'),
        ),
    ]
